name: Code, Test, Build Image and Deploy

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Get the current version
      id: version
      run: echo "::set-output name=version::0.1.0" # Initial version set to v0.1.0
      
    - name: Build and tag Docker image
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/todo-dev:$VERSION
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-dev:$VERSION

    - name: Debug Docker Hub Credentials
      run: |
        echo "DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}"
        echo "DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}"

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-dev:~v0.1

  test:
    runs-on: ubuntu-latest

    # needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Tests
      run: echo "Run your tests here"
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # - name: Install Dependencies
    #   run: npm install  # If you have npm dependencies

    - name: Serve HTML Application
      run: |
        npm install -g http-server  # Install a simple HTTP server
        http-server -p 8080 &  # Start the server in the background

    - name: Run Tests
      run: |
        # Install Puppeteer
        npm install puppeteer  # Puppeteer
        # npm test.js  # Puppeteer
    - name: Stop HTTP Server
      run: pkill -f http-server  # Stop the HTTP server

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to Cloud Platform
      run: echo "Deploy to your cloud platform here"
